# This file was generated by the {rix} R package v0.15.5 on 2025-03-14
# with following call:
# >rix(date = "2025-03-03",
#  > r_pkgs = c("dplyr",
#  > "ggplot2"),
#  > system_pkgs = c("python312",
#  > "python312Packages.pandas"),
#  > git_pkgs = NULL,
#  > tex_pkgs = NULL,
#  > ide = "positron",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.4.3")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-03-03.tar.gz") { config.allowUnfree = true; };
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      dplyr
      ggplot2;
  };
    
  py_pkgs = builtins.attrValues {
    inherit (pkgs.python312Packages) 
      pandas
	  pip
	  ipykernel;
  };
	
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      positron-bin
      python312
      R;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [  rpkgs py_pkgs system_packages   ];
  
}
